version: "3.1"
nlu:
- intent: bot_challenge
  examples: |
    - am I talking to a bot?
    - are you a human?
    - what are you?
    - are you a bot?
- intent: router_number_for_custom_network
  examples: |
    - [2](router_number) routers.
    - There will be [5](router_number) routers at the given network.
    - [10](router_number)
    - [5](router_number) router points.
- intent: affirm
  examples: |
    - of course
    - y
    - that sounds good
    - indeed
    - yes
- intent: upload_image
  examples: |
    - I want to show you the drawing of a network.
    - Can I provide you a network image.
    - I want to upload an image of a network.
    - I want to show the entities in a network topology image.
    - Can I show you the picture of a network topology.
- intent: ask_switch_network_scenario
  examples: |
    - Create a network example with hosts and switches.
    - Connect a machine to a virtual network, use a switch please.
    - Show me an example on how the network creation works with a switch?
    - Show me an example using a switch and more hosts.
    - Can you show me an example where a switch is used to connect hosts.
    - Create a network configuration example with more hosts and a switch.
- intent: deny
  examples: |
    - n
    - no
    - never
    - no way
    - I don't think so
- intent: ask_complex_network_scenario
  examples: |
    - Show me an example on how the network creation works?
    - Can you show me a complex example of a network.
    - Can you show me an example on a complex network scenario?
    - Show me an example with more hosts and more virtual networks.
    - Create a network example with hosts, routers and virtual bridges.
    - Connect a few machines to a virtual network, make it complex.
    - I want to create a complex network scenario.
- intent: provide_users_per_router
  examples: |
    - I want to have [1](user_number_for_router) user per router
    - [5](user_number_for_router) users using each router.
    - There will be [5](user_number_for_router) users at the given royter.
    - Users per router: [8](user_number_for_router)
    - [2](user_number_for_router) users per router.
    - [1](user_number_for_router) users for each router, please.
- intent: provide_users_to_network
  examples: |
    - I'm planning to configure [6](user_number_n) users for the network.
    - Assign [3](user_number_n) users to the network.
    - Allocate [5](user_number_n) users to each network in the setup.
    - There are [4](user_number_n) users connected to the network.
    - [4](user_number_n) users will be using the network for connectivity.
    - Network users: [8](user_number_n).
- intent: stop_all_request
  examples: |
    - Stop all the running network scenarios.
    - Stop all the running network simulations.
    - I want to stop all the running scenarios.
    - Stop all the running scenarios.
    - Stop all.
    - Stop running all things.
    - Stop all the running simulations.
    - I want to stop all the running networks.
- intent: create_custom_network_intent
  examples: |
    - I'd like to build a network with many users and routers.
    - What do I need to do to have a network with lots of users and routers?
    - I'm thinking of creating a network with many users and routers.
    - I want to create a network with many users and many routers.
    - Need advice on making a network with many users and routers.
    - How can I set up a network with lots of users and routers?
    - I want to make a big network with lots of users and routers.
- intent: switch_connection_request
  examples: |
    - I need to establish a connection to a switch.
    - Help me understand how to configure a switch for user connections.
    - I'm interested in connecting users through a switch.
    - Can you guide me on how to create a network using a switch?
    - I want to connect users to a switch.
    - I'm looking to connect users via a switch.
    - I'd like to establish connectivity through a switch.
- intent: ask_functionality
  examples: |
    - How does this tool benefit me?
    - How does this chatbot operate?
    - Describe the functionality of this tool.
    - In what ways can I use this chatbot?
    - Explain the features of this bot.
    - Tell me the functions of this tool.
    - What tasks can I perform with this bot?
    - What are the practical uses of this chatbot?
- intent: ask_general_question
  examples: |
    - I want to create a network with a large user base—where should I start?
    - How can I deploy a network with many users for testing purposes?
    - Provide guidance on creating a network with a substantial number of users.
    - Provide advice on creating a network with a large number of users.
    - What is the best way to create a network with a high number of users?
    - I'm interested in deploying a network with many users—any recommendations?
    - Guide me through the process of creating a network with numerous users.
    - Share insights on creating a network with a significant number of users.
- intent: goodbye
  examples: |
    - bye bye
    - bye
    - good night
    - have a nice day
    - goodbye
    - cu
    - see you around
    - cee you later
- intent: ask_network_diagram
  examples: |
    - Create a network map.
    - Display a network diagram.
    - Show me a network graphic.
    - Show a network map.
    - Show a diagram of the current network.
    - Show me the network diagram.
    - Do a network graphic.
    - Show me a network diagram.
- intent: provide_lan_users
  examples: |
    - [5](lan_user) users for the LAN.
    - I want to connect [5](lan_user) users using the LAN.
    - [5](lan_user) will use the LAN.
    - There are [4](lan_user) users connected to the LAN.
    - Allocate [5](lan_user) users to each LAN in the setup.
    - [5](lan_user) LAN users.
    - Each LAN will have [6](lan_user) users connected.
    - I'm planning to configure [6](lan_user) users for the LAN.
- intent: ask_vlan_switch_scenario
  examples: |
    - Please explain how VLANs are applied in a network environment.
    - Could you give me an illustration of how VLANs are implemented in a network?
    - I'm curious about VLAN usage. Could you walk me through a scenario that demonstrates it?
    - I'd like to see a practical example of a network setup that employs VLANs.
    - Could you provide an instance of a network configuration where VLANs play a role?
    - I want to understand VLANs in a real-world context. Can you describe a use case?
    - Show me an example on a scenario that uses a VLAN.
    - Can you describe a scenario where VLANs are used to segment a network?
    - Tell me about a network setup using VLANs.
- intent: switch_cisco_config_request
  examples: |
    - Give me cisco switch command details for many users.
    - Help me with cisco switch config for many users.
    - I want to know the switch command configuration for a cisco switch.
    - What's the cisco switch command for a large user group?
    - I need cisco switch command info for many users.
    - Tell me the cisco switch command config for lots of users.
    - What's the switch configuration setup for multiple users?
    - How do I set up cisco  switches for many users?
    - Explain cisco switch config for a bunch of users.
- intent: provide_users_to_switch
  examples: |
    - Switch config for [5](user_number) users
    - Allocate [3](user_number) users to the switch
    - [5](user_number) switch users
    - I want to have [1](user_number) switch users
    - Assign [5](user_number) users to the switch
    - Configure switch for [2](user_number) users
    - Set up switch for [1](user_number) user
    - [3](user_number) users will use the switch
- intent: provide_users_to_cisco_switch
  examples: |
    - Assign [5](user_number_cisco) users to the Cisco switch
    - Allocate [3](user_number_cisco) users to the Cisco switch
    - The configuration must be done for [5](user_number_cisco) users.
    - Cisco switch config for [5](user_number_cisco) users
    - There will be [2](user_number_cisco) users for the switch
    - Configure Cisco switch for [2](user_number_cisco) users
    - Cisco switch users: [8](user_number_cisco)
    - Set up Cisco switch for [1](user_number_cisco) user
    - There must be [1](user_number_cisco) switch users
- intent: create_network_intent
  examples: |
    - I want to use a router to connect to users.
    - Could you guide me through the steps of network creation?
    - I want to create a virtual network with a simple router.
    - I'd like to deploy a virtual network that use one router, where should I start?
    - What's the process for setting up a virtual network?
    - How can I create a network in this simulation using only one router?
    - I want to create and deploy a simple network .
    - I'm looking to establish a virtual network environment with a router.
    - Please assist me in creating a virtual network infrastructure using a router.
- intent: show_scenario_status
  examples: |
    - Show scenario status.
    - Can I see the status of the scenario?
    - Can I see how the network is going.
    - Show me the status of the network.
    - How is the scenario going?
    - Show me the status of the running scenario.
    - How is the network going?
    - What is the status of the scenario?
    - Show running network status.
- intent: provide_xml_path
  examples: |
    - [validatefile](xml_path).
    - [filevalidation](xml_path) is the file name.
    - [validationfile](xml_path).
    - File name: [validationconfig](xml_path).
    - The file is called [validatefile](xml_path).
    - The name of the file is [validationfile](xml_path).
    - [tobevalidated](xml_path).
    - The file is named [tobevalidated](xml_path).
    - [validatefile](xml_path) is the file name.
- intent: connect_two_computers_request
  examples: |
    - Hey, help me link up two computers!
    - I need to connect two users in a network, can you assist?
    - Connect two hosts.
    - Simply make a connection between two computers.
    - Make a connection between two computers
    - Could you assist in making a connection between two computers?
    - I want to connect two computers in a network.
    - I want to connect two hosts.
    - Any chance you can link two hosts together for me?
    - I want to connect two users in a network.
- intent: use_router_for_networking
  examples: |
    - The network should be configured using a router for connectivity.
    - I'd like to use a router to connect hosts in the network.
    - A router.
    - Use a router to establish connections between hosts in the network.
    - Router connectivity is the approach I want to take.
    - I want to rely on a router for networking purposes.
    - Router-based networking is my preference.
    - I prefer using a router for network connectivity.
    - The chosen device for networking will be a router.
    - Router-based networking suits my requirements.
- intent: use_switch_for_networking
  examples: |
    - Switch.
    - Switch-based networking suits my requirements.
    - Switch connectivity is the approach I want to take.
    - I'd like to use a switch to connect hosts in the network.
    - The chosen device for networking will be a switch.
    - A switch.
    - Use a switch to establish connections between hosts in the network.
    - I prefer using a switch for network connectivity.
    - The network should be configured using a switch for connectivity.
- intent: use_lan_for_networking
  examples: |
    - I prefer using a LAN for network connectivity.
    - I want to rely on a LAN for networking purposes.
    - LAN.
    - LAN-based networking suits my requirements.
    - A LAN.
    - The chosen device for networking will be a LAN.
    - LAN-based networking is my preference.
    - I'd like to use a LAN to connect hosts in the network.
    - I want to use a LAN.
    - The network should be configured using a LAN for connectivity.
- intent: connect_lan_request
  examples: |
    - Set up user connectivity using a LAN network.
    - Utilize a LAN network for user connectivity.
    - Establish a connection between users and a LAN network.
    - Facilitate user connection via a LAN network.
    - Use a LAN network to connect users.
    - Connect users through a LAN network.
    - Employ a LAN network to connect users.
    - Link users to the LAN for network access.
    - Establish user links through a LAN connection.
- intent: ask_xml_validation
  examples: |
    - Validate a VNX XML file.
    - Check the syntax of a XML config file.
    - Validate a XML config file.
    - Can you please validate a XML configuration file?
    - Validate a XML file.
    - Validate a XML configuration file.
    - I want to check the syntax of a XML file.
    - Check the syntax of a XML file.
    - If I give you a XML file can you check its syntax?
    - Validate a XML file for me.
    - I want to validate a XML configuration file.
- intent: mood_great
  examples: |
    - amazing
    - perfect
    - I am amazing
    - so so perfect
    - wonderful
    - I am going to save the world
    - I am great
    - super stoked
    - feeling like a king
    - great
    - so good
- intent: mood_unhappy
  examples: |
    - super sad
    - not good
    - my day was horrible
    - I'm so sad
    - so sad
    - so saad
    - unhappy
    - I am disappointed
    - I don't feel very well
    - extremly sad
    - very sad
- intent: greet
  examples: |
    - hey friend
    - good to see you
    - hi friend
    - hey team
    - hi there
    - hey buddy
    - good day
    - howdy
    - hi folks
    - morning
    - hi everyone
    - hey you
- intent: ask_simple_network_scenario
  examples: |
    - Show me an example of how the network creation works?
    - Provide me with an example of a simple network setup.
    - I'm interested in a tutorial on creating a straightforward virtual network.
    - Illustrate the process of connecting a machine to a virtual network.
    - Show me how to create a simple network environment.
    - Can you demonstrate a basic network configuration scenario?
    - Walk me through the steps of setting up a basic network scenario.
    - I'd like to see a sample scenario for connecting a machine to a virtual network.
    - How do I create a basic virtual network scenario?
    - Explain how to set up a virtual network with a single machine.
    - Share an instance of a basic network setup.
    - Please show me a practical example of network creation.
- intent: ask_basic_concepts
  examples: |
    - Explain the purpose of [gateway](network_device) devices.
    - Describe the role of a [router](network_device) devices in networks.
    - Explain [switch](network_device) devices.
    - What is the significance of [TCP/IP](network_device) in networking?
    - Tell me about a [router](network_device)
    - What's the function of a [router](network_device) in a network?
    - What is a [router](network_device) used for in networking?
    - What's the function of a [switch](network_device) in networking?
    - Explain the role of a [router](network_device) in a network.
    - Describe [subnetting](network_device) in networking.
    - Can you provide information about [router](network_device)?
    - How does [DNS](network_device) work in a network?
    - What is the purpose of a [router](network_device)?
